### ISSUE TITLE
[Question] adding Pages for another mod

### ISSUE THREAD

**Issue by beepbeat** [MineMaarten/IGW-mod#15]
My current project is to give AE2 some IGW-Wikipages, but with the current structure and code at https://github.com/beepbeat/Applied-Energistics-2/ it adds the WikiTab, but if I want to get infornation about the (currently only) registered Block, it cant find the page-file.
Maybe someone can help me.

Thanks in advance.

**Comment by MineMaarten** [comment]
if you place the block you're searching down, and press 'I' while looking at it, what does IGW say it's looking for?

**Comment by beepbeat** [comment]
it gives me a long path, sometimes with a double ", but it is really long, because of ae2 modid. it should be the same path.

**Comment by MineMaarten** [comment]
I'm not sure I lost track of this topic, the solution is: It needs to be in: 
assets/igwmod/wiki/en_US/block/ae2.craftingUnit.txt
instead of:
assets/igwmod/en_US/block/ae2.craftingUnit.txt

Sorry it's displayed wrong here :S. That's fixed in next version, where doing it in the assets/igwmod/wiki/ folder is also deprecated (but still working). The recommended way from next version on is to put the files in assets/<modid>/wiki/. 

Sorry for not being responsive!

**Comment by beepbeat** [comment]
is that double slash in "assets//wiki/" a mistake, or do I really need that?
