### ISSUE TITLE
IGW Crashing when trying to drill down to items/subtopics

### ISSUE THREAD

**Issue by utoc** [MineMaarten/IGW-mod#59]
Good morning!

I have a few crashes to report that seem to happen in both single and multiplayer., I'm able to open IGW via the i key and I can browse the main topics (Entities, Blocks, Compact Macines, things that have their own tabs on the left) but cannot click any blue, underlined links to any topics.  As soon as I click the blue, underlined topic, the game closes immediately.  I have removed BetterFPS, FastCraft and Optifine to test incompatibility to no avail.

Video Gif: http://imgur.com/2qPJaKr

(The crash happens right as the video loops)

IGW 1.1.9-29
Modlist here: https://www.reddit.com/r/BBQSauce/wiki/modlist
Mod versions here: https://www.reddit.com/r/BBQSauce/wiki/index/modver
The crash can be found here: http://pastebin.com/EGjxXrpJ

While I am waiting on a fix, do you have some documentation on the Wait/Text puzzle pieces?  I was trying to see how to use them in a drone I had made.  And WOW I am BLOWN AWAY with how awesome drones are.  You nailed it!

**Comment by MineMaarten** [comment]
Wow, this is going to be hard to find the root cause of this... The crash report is as vague as it could be (not your fault btw). Could you pastebin the full log (of the session), the one in the 'logs' folder?

Thanks for the Drone compliment ;). Until I fixed this, the only way to get updated information is to visit the raw assets of the wikipages, https://github.com/MineMaarten/PneumaticCraft/tree/master/resources/assets/pneumaticcraft/wiki/en_US/progwidget . It will contain formatting codes, but it has the info.

**Comment by utoc** [comment]
See log here: http://bbqsauce.terron.com/fml-client-latest.log and http://bbqsauce.terron.com/fml-client-2.log 

I can zip it up also, if you'd rather.  its 8mb and I can't send it to pastebin unfortunately.  The -2 log is the one that is not running FastCraft and Optifine.  Let me know how else I can assist :)
