### ISSUE TITLE
Suggestion: a way to reopen previous GUI, where appropriate

### ISSUE THREAD

**Issue by desht** [MineMaarten/IGW-mod#85]
I noticed this while testing IGW integration from the PNC Programmer; pressing 'I' over a widget goes to the right place in the wiki, but closing the wiki means you need to open the programmer GUI again, which is a (minor) annoyance.

Suggestion: add a method to GuiWiki to store a reference to the current GUI object if any, and in ``onGuiClosed()``, the stored GUI can be redisplayed, if it's been set.

Thoughts?  I can do a PR for that if you want...

**Comment by MineMaarten** [comment]
That sounds great! I will add that myself, because I will combine it with a little addition to the API, so that you don't need to reference non igwmod.api.* packages, for example to get hold of a GuiWiki to open it.

I could create an API hook to open the wiki GUI on a page with an optional return GUI.

**Comment by desht** [comment]
Sounds perfect :)

**Comment by MineMaarten** [comment]
Removing the need for referencing non igwmod.api.* packages currently is a bit more work, at least in the registry to IGW mod atm, so for now this will do.
